# Jekyll configuration

name: KCJ
title: Kurt's Blog
author: Kurt Jacobson
description: "Various posts related to mechanical engineering, industrial
automation, and programing."

# url is used for the RSS feed in feed.xml and for images in image-gallery.html
url: http://www.kcjengr.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

## default date_format
date_format:
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"

# Language
lan: "en"

paginate: 10

highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate', 'jekyll-seo-tag', 'jekyll-sitemap']

exclude: ['README.md', 'LICENSE', "*.bak"]
